# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/NEXYS4DDR_MASTER.xdc

# IP: C:/Users/Administrator/Downloads/audioFPGA/audio/audio.ip_user_files/xadc_wiz_0/xadc_wiz_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==xadc_wiz_0 || ORIG_REF_NAME==xadc_wiz_0} -quiet] -quiet
