# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.cache/wt [current_project]
set_property parent.project_path C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib -sv {
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/AnalogXADC.v
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/clk_div.sv
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/delay.sv
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/dist.sv
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/pwm.sv
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/reverb.sv
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/sram.sv
  C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/sources_1/new/top.sv
}
read_ip -quiet C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.ip_user_files/xadc_wiz_0/xadc_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.ip_user_files/xadc_wiz_0/xadc_wiz_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.ip_user_files/xadc_wiz_0/xadc_wiz_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/constrs_1/new/NEXYS4DDR_MASTER.xdc
set_property used_in_implementation false [get_files C:/Users/sraby1/Documents/GitHub/Nexys4-Audio/Audio/audio.srcs/constrs_1/new/NEXYS4DDR_MASTER.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
